### ISSUE TITLE
Unable to sign up!

### ISSUE THREAD

**Issue by lovebdsobuj** [c4goldsw/HandUp#1]
Trying to signup but always get **This password is incorrect.**

**Comment by c4goldsw** [comment]
Oops!  The text at the login screen isn't correct - I'm working on a commit and I'll change it to say "Sign in" once I'm finished with it.  Currently, making an account isn't a simple process (the accounts are managed by Pearson Learning Studio, an education management service).  As I don't intend on releasing the app, I will not implement a sign up feature.
